import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs";
import { Provider } from "@/components/ui/provider"
import "./globals.css";

/* testing fonts */
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      afterSignOutUrl="/"
      signInUrl={process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL}
      signInForceRedirectUrl={process.env.NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL}
      signInFallbackRedirectUrl={process.env.NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL}
      signUpForceRedirectUrl={process.env.NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL}
      signUpFallbackRedirectUrl={process.env.NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL}
    >
      <html suppressHydrationWarning>
        <head>
          <script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript" async />
        </head>
        <body suppressHydrationWarning className={`${inter.variable} ${montserrat.variable}`}>
          <Provider>{children}</Provider>
        </body>
      </html>
    </ClerkProvider>
  );  
}